FROM python:3.9-slim

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Make port 3000 available to the world outside this container
EXPOSE 3000

# Remove Dockerfile and requirements.txt after installation
RUN rm -f /app/Dockerfile /app/requirements.txt

# Run main.py when the container launches, use ssl
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "3000","--ssl-keyfile", "/app/server.key", "--ssl-certfile", "/app/server.crt"]
